services:

    _defaults:
        public: false
        autowire: true

    OxidAcademy\GraphQL\ProductExtension\:
        resource: 'src/*'
        public: true

    OxidAcademy\GraphQL\ProductExtension\Shared\Service\NamespaceMapper:
        class: OxidAcademy\GraphQL\ProductExtension\Shared\Service\NamespaceMapper
        tags: ['graphql_namespace_mapper']
